
token = 0
guildID = 0
prefix = "!"

[on_join]
enabled = false #enable on join messages
welcomeChannel = 0
welcomeMessage = "pls welcome {member} to the server!"
roleOnJoin = 0


[economy]
enabled = true #enable the economy features

[economy.cooldown]
# in minutes
workCooldown = 10 
begCooldown = 5
slutCooldown = 15