
token = "0"
guildID = 980870866638340166
prefix = "!"

[on_join]
enabled = false #enable on join messages
welcomeChannel = 980870867145871412
welcomeMessage = "pls welcome {member} to the server!"
roleOnJoin = 997412646523523102


[economy]
enabled = true #enable the economy features

[economy.cooldown]
# in minutes
workCooldown = 10 
begCooldown = 5
slutCooldown = 15